### ISSUE TITLE
Feeback problem for joint position controller

### ISSUE THREAD

**Issue by smithjoshua001** [corlab/rtt-core-extensions#5]
I've been using the lwr simulator to try and get the feedback for the joint angles, velocities, and torques, however, I noticed while using the joint position controller the feedback seems to be wrong. I've got each joint moving in a sinusoidal motion at different rates and here are the plots I get from them:
This one shows what I get when taking it directly from the LWR simulation ports.
![joint_pos_simulation](https://cloud.githubusercontent.com/assets/2492642/16526973/e87e2424-3fab-11e6-846c-eec5fecff793.png)
This one shows what I get from the feedback on the joint position controller.
![output](https://cloud.githubusercontent.com/assets/2492642/16526983/f852abea-3fab-11e6-8cf5-63a601523105.png)

Both are taken using the OCL file reporter.

**Comment by smithjoshua001** [comment]
Ah found the issue, I was looking at the wrong data, and actually it matches what the simulator provides

**Comment by swrede** [comment]
Never mind. Glad that this issues doesn't seem to be a real one... This reminds me of adding some test cases to prevent regressions. @xwavex What do you think about adding some reasonable tests?

**Comment by xwavex** [comment]
@swrede I agree, we should definitely do this!
