### ISSUE TITLE
RTT-Core extensions for Ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by DhruvKoolRajamani** [corlab/rtt-core-extensions#8]
Hi, I'm in the process of porting my code to ubuntu 16.04 LTS and my code depends on the rtt-core-extensions module. Any idea as to when the release will be available? And integration with orocos 2.9.1?

**Comment by xwavex** [comment]
The rtt-core-extensions do work with 16.04. since I am only developing on xenial. However, I have not yet properly tested it with Orocos 2.9.1. My guess would be that it would probably work out of the box, but I am not sure though. Did you try and it failed?

**Comment by xwavex** [comment]
I will close this issue for now...
